name: Gh-Pages

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Get Tag
        id: get_tag
        run: echo "tag=${GITHUB_REF##*/}" >> $GITHUB_ENV
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
      - uses: bluefireteam/flutter-gh-pages@v8
        with:
          baseHref: /flutterwebactions/
          webRenderer: canvaskit
          customArgs: --dart-define="version=${{ env.tag }}"
